// import "@glideapps/glide-data-grid/dist/index.css";
import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import type { Metadata } from 'next';

import mitr from '@/components/fonts/Mitr';
import { theme } from '@/styles/themes/theme';

import ReactQueryProvider from './ReactQueryProvider';

import '@mantine/core/styles.css';
import '@/styles/globals.css';
import '@/styles/tailwindPreflight.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<head>
				<ColorSchemeScript defaultColorScheme="light" />
			</head>
			<body className={mitr.className} suppressHydrationWarning>
				<ReactQueryProvider>
					<ReactQueryDevtools initialIsOpen={false} />
					<MantineProvider theme={theme}>{children}</MantineProvider>
				</ReactQueryProvider>
			</body>
		</html>
	);
}
