import "@mantine/core/styles.css";
import "@/styles/globals.css";
// import "@glideapps/glide-data-grid/dist/index.css";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import type { Metadata } from "next";
import { theme } from "@/styles/themes/theme";
import mitr from "@/components/fonts/Mitr";
import ReactQueryProvider from "./ReactQueryProvider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <head>
                <ColorSchemeScript defaultColorScheme="light" />
            </head>
            <body className={mitr.className} suppressHydrationWarning>
                <ReactQueryProvider>
                    <ReactQueryDevtools initialIsOpen={false} />
                    <MantineProvider theme={theme}>{children}</MantineProvider>
                </ReactQueryProvider>
            </body>
        </html>
    );
}
